//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace II_VI_Incorporated_SCM.Models
{
    using System;
    
    public partial class sp_SOR_RiskShip_Report1_Result1
    {
        public string Type { get; set; }
        public int Current_Month { get; set; }
        public int Next_Month { get; set; }
    }
}
